### ISSUE TITLE
При сборке проекта не выполняется poetry install.

### ISSUE THREAD

**Issue by catboy1989** [aytmamatov/flavor_finder_backend#19]
При сборке проекта не выполняется poetry install.
Я вызвал команду в командной строке windows из папки проекта (flavor_finder_backend), на что получил ответ:

poetry не является внутренней или внешней командой, исполняемой программой или пакетным файлом.

**Comment by aytmamatov** [comment]
Попробуйте установить `poetry`, командой `pip install poetry`, если хотите глобально использовать, то можете добавить флаг `--global`.

**Comment by catboy1989** [comment]
Попробовал. Получил ответ:
pip не является внутренней или внешней командой, исполняемой программой или пакетным файлом. 
Догадываюсь, что у меня много чего не установлено для работы с вашим проектом...может есть смысл описать в readme всё, что необходимо установить, чтобы всё точно работало?

**Comment by aytmamatov** [comment]
Благодарю за фидбек, возможно вы не установили python и pip, вы можете это сделать тут https://www.python.org/downloads/, с версии python 3.4 pip идёт по умолчанию.

**Comment by catboy1989** [comment]
Благодарю! Теперь команда выполняется.
